services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=solta'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=spring'
      - 'MYSQL_CHARSET=utf8mb4'
      - 'MYSQL_COLLATION=utf8mb4_unicode_ci'
    ports:
      - '3307:3306'
    volumes:
      - ./src/main/resources/csv:/var/lib/mysql-files
