spring:
  application.name: solta
  config:
    import:
      - db.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ahmadda?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: solta
    password: ${db.local.password}

